#!/bin/bash

set -e

HAS_LOCAL_BIN=1

if [ ! -d "${HOME}/.local/bin" ]; then
  HAS_LOCAL_BIN=0
  mkdir -p ${HOME}/.local/bin
fi

TMP=$(mktemp -d)
LOC=$(pwd)

cd $TMP
git clone --quiet https://github.com/jamesob/brocrypt.git
cd brocrypt
if [ "$(uname)" == "Darwin" ]; then
  echo
  echo "!!! Assuming you've already run 'brew install openssl'..."
  echo
  pip install --global-option=build_ext --global-option="-L/usr/local/opt/openssl/lib" --global-option="-I/usr/local/opt/openssl/include" .
else
  python setup.py --quiet install --user
fi

echo "✨ installed brocrypt to ~/.local/bin/brocrypt"

if [ "$HAS_LOCAL_BIN" == "0" ]; then 
  echo '!!! add PATH=${HOME}/.local/bin:${PATH} to your shell rc file'
fi

cd "${LOC}"
rm -rf "${TMP}"
